services:
  postgres:
    image: 'postgres:18.6'
    command: postgres -c jit=off -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=elixir_lab_dev
    volumes:
      - 'docker_postgres:/var/lib/postgresql'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d elixir_lab_dev']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    profiles: [dependent-services]

volumes:
  docker_postgres:
